# Dark Souls II Reviews (2025)

In [1]:
from get_data import *
from bertopic import BERTopic

In [2]:
reviews = get_data()

In [4]:
reviews.update_date = pd.to_datetime(reviews["update_date"], unit='s')#.dt.date

- Scholar of the First Sin Edition launched: 4/1/2015

In [5]:
sotfs_start = pd.Timestamp("2015-04-01")
df = reviews[(reviews["update_date"] >= sotfs_start)]

In [6]:
scholar = df[df.review.str.contains(r'\bscholar\b')]
scholar

review language  \
recommendationid                                                               
182542126         scholar like fart poo smellers shart absolute ...  english   
175344650         clunky vast majority boss joke lot player anim...  english   
155880905         great flawed note insanely low hour gameplay p...  english   
148841626         thing much good thing ii especially scholar ve...  english   
143099632         probably weak entry trilogy still great schola...  english   
141982729         simple sotfs far hard complete ncels absolutel...  english   
137525608         preface bit fromsoft detractor however pretty ...  english   
128821300         scholar mixed bag compare launch day version h...  english   
110725895         unfortunately differs entry series death often...  english   
105347236         buy ii expect great buy scholar hop fix broken...  english   
105242729         unfairly hat good mainly due straightforward l...  english   
98452386          amazing play solo co op friend sotfs scholar o...  english   
96140675          real talk get issue scholar original actually ...  english   
94913183          remember bed chaos bed chaos series fact even ...  english   
94094484          weird fromsoftware soulslike probably main tea...  english   
79478925          backstory play completion inspire give like ga...  english   
79222792          black sheep soulsborne game personal favorite ...  english   
72370515          still long series many huge dlcs scholar defin...  english   
68260406          put hour finally review review two part like g...  english   
52651158          scholar brutal complete regular version absolu...  english   
39223729          play hundred hour apiece plan play never want ...  english   
33350171          scholar good widely regard bad agree still goo...  english   
29709006          truly believe bandai namco software excellent ...  english   
27431128                                 avici simulator ii scholar  english   
26381355          many write bad series however let comment fool...  english   
24753827          ii scholar review oh ii know start honestly im...  english   
24548418          holy crap two word use dozen time still get sa...  english   
22504145          ah series unfinished masterpiece leave quite d...  english   
21449486          play beat prepare die fan series play original...  english   
21228305          love hate relationship one hand bad hand hand ...  english   
20581257          original ii great challenging scholar also goo...  english   
19930982          play original scholar test skill many change m...  english   
16007532          play original get near end ng one scholar say ...  english   
15225920          play lot dks graphic change underwhelming like...  english   

                   init_date         update_date  in_early_access  voted_up  \
recommendationid                                                              
182542126         1733972158 2024-12-12 03:43:36            False      True   
175344650         1726798767 2024-09-20 02:19:27            False     False   
155880905         1705145738 2024-01-15 14:14:02            False      True   
148841626         1698229728 2023-10-25 10:30:09            False      True   
143099632         1690741402 2023-07-30 18:23:22            False      True   
141982729         1689252027 2023-07-13 12:41:39            False      True   
137525608         1682823473 2023-04-30 02:57:53            False      True   
128821300         1671404887 2022-12-18 23:08:07            False      True   
110725895         1645485557 2022-02-21 23:19:17            False     False   
105347236         1638788477 2021-12-06 11:02:49            False     False   
105242729         1638651730 2021-12-04 21:03:09            False      True   
98452386          1630250968 2021-08-29 15:29:28            False      True   
96140675          1626885127 2021-07-21 16:32:07            False      Tru

In [7]:
topic_model = BERTopic.load("models/bertopic_model")
topics, probs = topic_model.transform(scholar.review.values)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

In [8]:
t = topic_model.get_topic_info()
t[t.Topic.isin(np.unique(topics))]

Topic  Count                                       Name  \
0       -1  16198                  -1_death_trash_play_rolin   
2        1   1239                  1_attack_area_enemy_fight   
9        8    297             8_world_sequel_story_franchise   
71      70     75                  70_simulator_sim_alt_liar   
262    261     29  261_original_placement_improvement_change   

                                        Representation  \
0    [death, trash, play, rolin, game, series, like...   
2    [attack, area, enemy, fight, player, bos, weap...   
9    [world, sequel, story, franchise, design, game...   
71   [simulator, sim, alt, liar, slice, date, baboo...   
262  [original, placement, improvement, change, wil...   

                                   Representative_Docs  
0    [bad soulsborne huge margin even come close qu...  
2    [oh god talk always tricky topic talk director...  
9    [ii second chapter franchise get lot hate stra...  
71     [death simulator, die simulator, fun simulator]  
262  [massive improvement enemy placement enough ch...

In [9]:
topics, probs

([-1,
  -1,
  -1,
  -1,
  -1,
  1,
  1,
  -1,
  -1,
  1,
  -1,
  -1,
  261,
  1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  1,
  1,
  -1,
  70,
  -1,
  1,
  -1,
  -1,
  -1,
  8,
  -1,
  -1,
  -1,
  1],
 array([0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.43112062, 0.        , 0.        , 0.50370361,
        0.        , 0.        , 0.8539028 , 0.81357107, 0.        ,
        0.        , 0.        , 0.        , 0.6210403 , 0.        ,
        0.80354586, 0.84182771, 0.        , 0.25959522, 0.        ,
        0.48684928, 0.        , 0.        , 0.        , 0.96205341,
        0.        , 0.        , 0.        , 0.48039379]))

In [10]:
topic_pos_model = BERTopic.load("models/bertopic_pos_model")
pos_topics, pos_probs = topic_pos_model.transform(scholar.review.values)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

In [11]:
t = topic_pos_model.get_topic_info()
t[t.Topic.isin(np.unique(pos_topics))]

Topic  Count                              Name  \
0       -1  13309           -1_death_play_game_love   
3        2    823        2_area_enemy_attack_player   
49      48     80          48_simulator_aid_sim_alt   
259    258     26  258_trilogy_weak_uncouthed_tribe   

                                        Representation  \
0    [death, play, game, love, series, recommend, g...   
3    [area, enemy, attack, player, fight, weapon, b...   
49   [simulator, aid, sim, alt, simp, murderous, wa...   
259  [trilogy, weak, uncouthed, tribe, extinct, phi...   

                                   Representative_Docs  
0    [feel like almost try one add weird mechanic c...  
3    [let preface review say lot fearmongering relu...  
49     [death simulator, die simulator, fun simulator]  
259  [definitely weak one trilogy still great reall...

In [12]:
pos_topics, pos_probs

([-1,
  -1,
  2,
  -1,
  258,
  2,
  2,
  -1,
  -1,
  2,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  2,
  -1,
  2,
  2,
  -1,
  48,
  -1,
  2,
  -1,
  -1,
  2,
  -1,
  -1,
  -1,
  -1,
  2],
 array([0.        , 0.        , 0.37269516, 0.        , 1.        ,
        0.42987514, 0.66668778, 0.        , 0.        , 0.73903625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.94909989, 0.        ,
        0.85174553, 0.8950909 , 0.        , 0.29762305, 0.        ,
        0.47405724, 0.        , 0.        , 0.39790695, 0.        ,
        0.        , 0.        , 0.        , 0.40213631]))

In [13]:
topic_neg_model = BERTopic.load("models/bertopic_neg_model")
neg_topics, neg_probs = topic_neg_model.transform(scholar.review.values)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

In [14]:
t = topic_neg_model.get_topic_info()
t[t.Topic.isin(np.unique(neg_topics))]

Topic  Count                                  Name  \
0       -1   3466                -1_like_play_enemy_get   
1        0    306             0_enemy_player_bos_attack   
107    106     13  106_original_version_placement_enemy   

                                        Representation  \
0    [like, play, enemy, get, make, bad, good, game...   
1    [enemy, player, bos, attack, area, fight, make...   
107  [original, version, placement, enemy, spam, re...   

                                   Representative_Docs  
0    [spoiler ahead play twice anticipation year la...  
1    [playthrough live reputation bad story engagin...  
107  [get rule original opinion change way much pla...

In [15]:
neg_topics, neg_probs

([-1,
  -1,
  -1,
  -1,
  -1,
  0,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  106,
  0,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1],
 array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.61954921, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.96444069, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.73321528, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]))